### PR TITLE
FDL-9350 / Use new model ingestion methods

### PR DESCRIPTION
**Pull request by lgenuit**
[FDL-9350](https://fiddlerlabs.atlassian.net/browse/FDL-9350)

Update the notebooks to remove any references to `register_model` and `upload_model_package`. Instead we use `add_model`, `add_model_surrogate` and `add_model_artifact`

[FDL-9350]: https://fiddlerlabs.atlassian.net/browse/FDL-9350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by mshergad** [comment]
@lgenuit would it make sense for us to set up a call where you can show me these notebooks on your local system for this branch?

**Comment by lgenuit** [comment]
@mshergad we can but you can also saw those locally. You just need to checkout locally to my branch and you can open those in your jupyter.

**Comment by mshergad** [comment]
okay cool, makes sense - will do

**Review by mshergad — CHANGES_REQUESTED** [review]
hey Lea, check the comments

**Comment by mshergad** [comment]
@lgenuit thanks! will do tomorrow latest Monday

**Review by mshergad — APPROVED** [review]
LGTM

**Pull request merged**
